import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  route("sitemap.xml", "routes/sitemap[.]xml.tsx"),
  route("robots.txt", "routes/robots[.]txt.tsx"),
  route("llms.txt", "routes/llms[.]txt.tsx"),
  layout("routes/_nav.tsx", [
    index("routes/home.tsx"),
    route("about", "routes/about.tsx"),
    route("indie-hackers", "routes/indie-hackers.tsx"),
    route("ai-builders", "routes/ai-builders.tsx"),
    route("saas-founders", "routes/saas-founders.tsx"),
    route("dashboard", "routes/launch.tsx"),
    route("extensions", "routes/extensions.tsx"),
    route("topup", "routes/topup.tsx"),
    route("tos", "routes/tos.tsx"),
    route("privacy-policy", "routes/privacy-policy.tsx"),
  ]),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("auth/callback", "routes/auth.callback.tsx"),
  route("logout", "routes/logout.tsx"),
  route("billing/success", "routes/billing.success.tsx"),
  route("billing/cancel", "routes/billing.cancel.tsx"),
  route("og", "routes/og.tsx"),
  route("extension-promo", "routes/extension-promo.1.tsx"),
  route("extension-promo-2", "routes/extension-promo.2.tsx"),
  route("extension-promo-3", "routes/extension-promo.3.tsx"),
  route("extension-promo-4", "routes/extension-promo.4.tsx"),
] satisfies RouteConfig;
