/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register user
         * @description Create a new user account and return access and refresh JWT tokens.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login user
         * @description Authenticate with email and password, then return access and refresh JWT tokens.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh tokens
         * @description Validate a refresh token and issue a new access and refresh JWT token pair.
         */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Return the authenticated user's profile derived from the bearer access token.
         */
        get: operations["get_current_user_info_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brand/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new project
         * @description Create a new project for a domain.
         */
        post: operations["create_project_api_v1_brand_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brand/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project
         * @description Get a project by ID.
         */
        get: operations["get_project_api_v1_brand_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brand/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract brand profile
         * @description Scrape a website and extract brand profile using AI agents.
         */
        post: operations["extract_brand_profile_api_v1_brand_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brand/projects/{project_id}/brand-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get brand profile
         * @description Get the brand profile for a project.
         */
        get: operations["get_brand_profile_api_v1_brand_projects__project_id__brand_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List directories
         * @description Get a paginated list of directories with optional filtering.
         */
        get: operations["list_directories_api_v1_directories__get"];
        put?: never;
        /**
         * Create directory
         * @description Create a new directory listing platform.
         */
        post: operations["create_directory_api_v1_directories__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directories/scrape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scrape and analyze directory
         * @description Scrape a directory website and extract information using AI. Optionally save to database.
         */
        post: operations["scrape_directory_api_v1_directories_scrape_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directories/{directory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get directory
         * @description Get a directory by ID.
         */
        get: operations["get_directory_api_v1_directories__directory_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete directory
         * @description Delete a directory by ID.
         */
        delete: operations["delete_directory_api_v1_directories__directory_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update directory
         * @description Update a directory by ID.
         */
        patch: operations["update_directory_api_v1_directories__directory_id__patch"];
        trace?: never;
    };
    "/api/v1/directories/{directory_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify directory
         * @description Mark a directory as verified with current timestamp.
         */
        post: operations["verify_directory_api_v1_directories__directory_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directories/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get directory statistics
         * @description Get summary statistics about directories.
         */
        get: operations["get_directory_stats_api_v1_directories_stats_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BrandExtractionRequest
         * @description Request to extract brand profile from domain.
         */
        BrandExtractionRequest: {
            /**
             * Domain
             * @description Domain to extract brand profile from (e.g., example.com)
             */
            domain: string;
            /**
             * Additional Context
             * @description Additional context about the brand or what to focus on
             */
            additional_context?: string | null;
        };
        /**
         * BrandProfileResponse
         * @description Response with extracted brand profile.
         */
        BrandProfileResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Company Name */
            company_name?: string | null;
            /** Tagline */
            tagline?: string | null;
            /** Products Services */
            products_services?: {
                [key: string]: unknown;
            }[] | null;
            /** Money Pages */
            money_pages?: {
                [key: string]: unknown;
            }[] | null;
            /** Unique Value Props */
            unique_value_props?: string[] | null;
            /** Differentiators */
            differentiators?: string[] | null;
            /** Target Roles */
            target_roles?: string[] | null;
            /** Target Industries */
            target_industries?: string[] | null;
            /** Company Sizes */
            company_sizes?: string[] | null;
            /** Primary Pains */
            primary_pains?: string[] | null;
            /** Desired Outcomes */
            desired_outcomes?: string[] | null;
            /** Objections */
            objections?: string[] | null;
            /** Tone Attributes */
            tone_attributes?: string[] | null;
            /** Allowed Claims */
            allowed_claims?: string[] | null;
            /** Restricted Claims */
            restricted_claims?: string[] | null;
            /** In Scope Topics */
            in_scope_topics?: string[] | null;
            /** Out Of Scope Topics */
            out_of_scope_topics?: string[] | null;
            /** Brand Assets */
            brand_assets?: {
                [key: string]: unknown;
            }[] | null;
            /** Visual Style Guide */
            visual_style_guide?: {
                [key: string]: unknown;
            } | null;
            /** Visual Prompt Contract */
            visual_prompt_contract?: {
                [key: string]: unknown;
            } | null;
            /** Extraction Confidence */
            extraction_confidence?: number | null;
            /** Visual Extraction Confidence */
            visual_extraction_confidence?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DirectoryCreateRequest
         * @description Request to create a new directory.
         */
        DirectoryCreateRequest: {
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /** Url */
            url: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Niche */
            niche?: string | null;
            /** Tags */
            tags?: string[] | null;
            /**
             * Is Dofollow
             * @default false
             */
            is_dofollow: boolean;
            /**
             * Link Type
             * @description dofollow, nofollow, ugc, sponsored
             */
            link_type?: string | null;
            /** Submission Url */
            submission_url?: string | null;
            /** Submission Guidelines */
            submission_guidelines?: string | null;
            /** Submission Requirements */
            submission_requirements?: string[] | null;
            /**
             * Submission Process
             * @description manual, automated, API
             */
            submission_process?: string | null;
            /**
             * Requires Approval
             * @default true
             */
            requires_approval: boolean;
            /** Typical Approval Time Days */
            typical_approval_time_days?: number | null;
            /**
             * Is Free
             * @default true
             */
            is_free: boolean;
            /**
             * Pricing Model
             * @description free, freemium, paid, one-time, subscription
             */
            pricing_model?: string | null;
            /** Price Usd */
            price_usd?: number | null;
            /** Pricing Details */
            pricing_details?: string | null;
            /** Domain Authority */
            domain_authority?: number | null;
            /** Monthly Traffic */
            monthly_traffic?: number | null;
            /** Alexa Rank */
            alexa_rank?: number | null;
            /** Spam Score */
            spam_score?: number | null;
            /** Contact Email */
            contact_email?: string | null;
            /** Support Url */
            support_url?: string | null;
            /**
             * Api Available
             * @default false
             */
            api_available: boolean;
            /** Api Documentation Url */
            api_documentation_url?: string | null;
            /**
             * Status
             * @description active, inactive, broken, pending_review
             * @default active
             */
            status: string;
            /** Quality Score */
            quality_score?: number | null;
            /** Verification Notes */
            verification_notes?: string | null;
            /** Target Audience */
            target_audience?: string[] | null;
            /** Supported Industries */
            supported_industries?: string[] | null;
            /** Features */
            features?: string[] | null;
            /** Benefits */
            benefits?: string[] | null;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Country */
            country?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Internal Notes */
            internal_notes?: string | null;
            /**
             * Recommended Priority
             * @default 5
             */
            recommended_priority: number;
        };
        /**
         * DirectoryInfo
         * @description Extracted directory information output.
         */
        DirectoryInfo: {
            /**
             * Name
             * @description Name of the directory
             */
            name: string;
            /**
             * Description
             * @description Description of what the directory is for
             */
            description?: string | null;
            /**
             * Category
             * @description Main category (e.g., 'Startup Directories', 'SaaS Directories', 'Product Hunt Alternatives')
             */
            category?: string | null;
            /**
             * Niche
             * @description Specific niche (e.g., 'B2B SaaS', 'AI Tools', 'No-Code')
             */
            niche?: string | null;
            /**
             * Tags
             * @description Relevant tags for categorization
             */
            tags?: string[];
            /**
             * Is Dofollow
             * @description Whether links from this directory are dofollow (good for SEO)
             * @default false
             */
            is_dofollow: boolean;
            /**
             * Link Type
             * @description Type of link: dofollow, nofollow, ugc, sponsored, or mixed
             */
            link_type?: string | null;
            /**
             * Link Analysis Confidence
             * @description Confidence in the link type analysis
             */
            link_analysis_confidence: number;
            /**
             * Submission Url
             * @description URL where users can submit their product/app
             */
            submission_url?: string | null;
            /**
             * Submission Guidelines
             * @description Guidelines or rules for submission
             */
            submission_guidelines?: string | null;
            /**
             * Submission Requirements
             * @description List of requirements (e.g., 'Logo required', 'Working website', 'English only')
             */
            submission_requirements?: string[];
            /**
             * Submission Process
             * @description How submission works: manual, automated, API, or hybrid
             */
            submission_process?: string | null;
            /**
             * Requires Approval
             * @description Whether submissions need to be approved/reviewed
             * @default true
             */
            requires_approval: boolean;
            /**
             * Typical Approval Time Days
             * @description Estimated days for approval (if mentioned)
             */
            typical_approval_time_days?: number | null;
            /**
             * Is Free
             * @description Whether the directory has a free listing option
             * @default true
             */
            is_free: boolean;
            /**
             * Pricing Model
             * @description Pricing model: free, freemium, paid, one-time, subscription
             */
            pricing_model?: string | null;
            /**
             * Price Usd
             * @description Price in USD if single pricing tier
             */
            price_usd?: number | null;
            /**
             * Pricing Details
             * @description Detailed pricing information including tiers
             */
            pricing_details?: string | null;
            /**
             * Contact Email
             * @description Contact email
             */
            contact_email?: string | null;
            /**
             * Support Url
             * @description Support or help page URL
             */
            support_url?: string | null;
            /**
             * Api Available
             * @description Whether they offer an API
             * @default false
             */
            api_available: boolean;
            /**
             * Api Documentation Url
             * @description API documentation URL
             */
            api_documentation_url?: string | null;
            /**
             * Target Audience
             * @description Who uses this directory (e.g., 'B2B', 'B2C', 'SaaS founders', 'Developers')
             */
            target_audience?: string[];
            /**
             * Supported Industries
             * @description Industries or verticals supported
             */
            supported_industries?: string[];
            /**
             * Features
             * @description Features offered (e.g., 'Featured listings', 'Analytics', 'Backlink')
             */
            features?: string[];
            /**
             * Benefits
             * @description Benefits of listing (e.g., 'SEO boost', 'Traffic', 'Brand awareness')
             */
            benefits?: string[];
            /**
             * Estimated Quality Score
             * @description Estimated quality score based on professionalism, content quality, etc.
             */
            estimated_quality_score?: number | null;
            /**
             * Recommended Priority
             * @description Recommended priority for submissions (1=highest, 10=lowest)
             * @default 5
             */
            recommended_priority: number;
            /**
             * Language
             * @description Primary language of the directory
             * @default en
             */
            language: string;
            /**
             * Country
             * @description Primary country if region-specific
             */
            country?: string | null;
            /**
             * Extraction Confidence
             * @description Overall confidence in the extraction (0-1)
             */
            extraction_confidence: number;
            /**
             * Extraction Notes
             * @description Notes about the extraction, ambiguities, or assumptions
             */
            extraction_notes?: string | null;
        };
        /**
         * DirectoryListResponse
         * @description Response with list of directories and pagination.
         */
        DirectoryListResponse: {
            /** Directories */
            directories: components["schemas"]["DirectoryResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * DirectoryResponse
         * @description Response with directory information.
         */
        DirectoryResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /** Url */
            url: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Niche */
            niche?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Is Dofollow */
            is_dofollow: boolean;
            /** Link Type */
            link_type?: string | null;
            /** Submission Url */
            submission_url?: string | null;
            /** Submission Guidelines */
            submission_guidelines?: string | null;
            /** Submission Requirements */
            submission_requirements?: string[] | null;
            /** Submission Process */
            submission_process?: string | null;
            /** Requires Approval */
            requires_approval: boolean;
            /** Typical Approval Time Days */
            typical_approval_time_days?: number | null;
            /** Is Free */
            is_free: boolean;
            /** Pricing Model */
            pricing_model?: string | null;
            /** Price Usd */
            price_usd?: number | null;
            /** Pricing Details */
            pricing_details?: string | null;
            /** Domain Authority */
            domain_authority?: number | null;
            /** Monthly Traffic */
            monthly_traffic?: number | null;
            /** Alexa Rank */
            alexa_rank?: number | null;
            /** Spam Score */
            spam_score?: number | null;
            /** Contact Email */
            contact_email?: string | null;
            /** Support Url */
            support_url?: string | null;
            /** Api Available */
            api_available: boolean;
            /** Api Documentation Url */
            api_documentation_url?: string | null;
            /** Status */
            status: string;
            /** Quality Score */
            quality_score?: number | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Verification Notes */
            verification_notes?: string | null;
            /** Target Audience */
            target_audience?: string[] | null;
            /** Supported Industries */
            supported_industries?: string[] | null;
            /** Features */
            features?: string[] | null;
            /** Benefits */
            benefits?: string[] | null;
            /** Success Stories */
            success_stories?: {
                [key: string]: unknown;
            }[] | null;
            /** Testimonials */
            testimonials?: {
                [key: string]: unknown;
            }[] | null;
            /** Language */
            language: string;
            /** Country */
            country?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Internal Notes */
            internal_notes?: string | null;
            /** Recommended Priority */
            recommended_priority: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DirectoryScrapeRequest
         * @description Request to scrape and analyze a directory.
         */
        DirectoryScrapeRequest: {
            /** Domain */
            domain: string;
            /** Additional Context */
            additional_context?: string | null;
            /**
             * Auto Save
             * @default false
             */
            auto_save: boolean;
        };
        /**
         * DirectoryScrapeResponse
         * @description Response from directory scraping.
         */
        DirectoryScrapeResponse: {
            directory_info: components["schemas"]["DirectoryInfo"];
            /**
             * Saved
             * @default false
             */
            saved: boolean;
            /** Directory Id */
            directory_id?: string | null;
        };
        /**
         * DirectoryUpdateRequest
         * @description Request to update a directory.
         */
        DirectoryUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Domain */
            domain?: string | null;
            /** Url */
            url?: string | null;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /** Niche */
            niche?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Is Dofollow */
            is_dofollow?: boolean | null;
            /** Link Type */
            link_type?: string | null;
            /** Submission Url */
            submission_url?: string | null;
            /** Submission Guidelines */
            submission_guidelines?: string | null;
            /** Submission Requirements */
            submission_requirements?: string[] | null;
            /** Submission Process */
            submission_process?: string | null;
            /** Requires Approval */
            requires_approval?: boolean | null;
            /** Typical Approval Time Days */
            typical_approval_time_days?: number | null;
            /** Is Free */
            is_free?: boolean | null;
            /** Pricing Model */
            pricing_model?: string | null;
            /** Price Usd */
            price_usd?: number | null;
            /** Pricing Details */
            pricing_details?: string | null;
            /** Domain Authority */
            domain_authority?: number | null;
            /** Monthly Traffic */
            monthly_traffic?: number | null;
            /** Alexa Rank */
            alexa_rank?: number | null;
            /** Spam Score */
            spam_score?: number | null;
            /** Contact Email */
            contact_email?: string | null;
            /** Support Url */
            support_url?: string | null;
            /** Api Available */
            api_available?: boolean | null;
            /** Api Documentation Url */
            api_documentation_url?: string | null;
            /** Status */
            status?: string | null;
            /** Quality Score */
            quality_score?: number | null;
            /** Last Verified At */
            last_verified_at?: string | null;
            /** Verification Notes */
            verification_notes?: string | null;
            /** Target Audience */
            target_audience?: string[] | null;
            /** Supported Industries */
            supported_industries?: string[] | null;
            /** Features */
            features?: string[] | null;
            /** Benefits */
            benefits?: string[] | null;
            /** Language */
            language?: string | null;
            /** Country */
            country?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Internal Notes */
            internal_notes?: string | null;
            /** Recommended Priority */
            recommended_priority?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ProjectCreateRequest
         * @description Request to create a new project.
         */
        ProjectCreateRequest: {
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /** Description */
            description?: string | null;
            /**
             * Primary Language
             * @default en
             */
            primary_language: string;
            /**
             * Primary Locale
             * @default en-US
             */
            primary_locale: string;
            /**
             * Posts Per Week
             * @default 1
             */
            posts_per_week: number;
        };
        /**
         * ProjectResponse
         * @description Response with project information.
         */
        ProjectResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /** Description */
            description?: string | null;
            /** Primary Language */
            primary_language: string;
            /** Primary Locale */
            primary_locale: string;
            /** Posts Per Week */
            posts_per_week: number;
            /** Current Step */
            current_step: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * Token
         * @description Schema for JWT token response.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TokenRefresh
         * @description Schema for token refresh request.
         */
        TokenRefresh: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * UserCreate
         * @description Schema for user registration.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /**
         * UserLogin
         * @description Schema for user login.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description Schema for user response.
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Superuser */
            is_superuser: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    create_project_api_v1_brand_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_brand_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_brand_profile_api_v1_brand_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrandExtractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brand_profile_api_v1_brand_projects__project_id__brand_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_directories_api_v1_directories__get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
                /** @description Filter by category */
                category?: string | null;
                /** @description Filter by niche */
                niche?: string | null;
                /** @description Filter by dofollow status */
                is_dofollow?: boolean | null;
                /** @description Filter by free status */
                is_free?: boolean | null;
                /** @description Filter by status */
                status?: string | null;
                /** @description Minimum domain authority */
                min_domain_authority?: number | null;
                /** @description Maximum spam score */
                max_spam_score?: number | null;
                /** @description Minimum quality score */
                min_quality_score?: number | null;
                /** @description Search in name, domain, or description */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_directory_api_v1_directories__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectoryCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scrape_directory_api_v1_directories_scrape_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectoryScrapeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryScrapeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_directory_api_v1_directories__directory_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                directory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_directory_api_v1_directories__directory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                directory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_directory_api_v1_directories__directory_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                directory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_directory_api_v1_directories__directory_id__verify_post: {
        parameters: {
            query?: {
                verification_notes?: string | null;
            };
            header?: never;
            path: {
                directory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_directory_stats_api_v1_directories_stats_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
